// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"
	mock "github.com/stretchr/testify/mock"
)

// DoguValidator is an autogenerated mock type for the DoguValidator type
type DoguValidator struct {
	mock.Mock
}

// ValidateDogus provides a mock function with given fields: dogus
func (_m *DoguValidator) ValidateDogus(dogus context.Dogus) error {
	ret := _m.Called(dogus)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Dogus) error); ok {
		r0 = rf(dogus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
