// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"
	mock "github.com/stretchr/testify/mock"
)

// NamingValidator is an autogenerated mock type for the NamingValidator type
type NamingValidator struct {
	mock.Mock
}

// ValidateNaming provides a mock function with given fields: naming
func (_m *NamingValidator) ValidateNaming(naming context.Naming) error {
	ret := _m.Called(naming)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Naming) error); ok {
		r0 = rf(naming)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
