// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"
	mock "github.com/stretchr/testify/mock"
)

// RegistryConfigEncryptedValidator is an autogenerated mock type for the RegistryConfigEncryptedValidator type
type RegistryConfigEncryptedValidator struct {
	mock.Mock
}

// ValidateRegistryConfigEncrypted provides a mock function with given fields: config
func (_m *RegistryConfigEncryptedValidator) ValidateRegistryConfigEncrypted(config *context.SetupConfiguration) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.SetupConfiguration) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
