// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"
	mock "github.com/stretchr/testify/mock"
)

// UserBackendValidator is an autogenerated mock type for the UserBackendValidator type
type UserBackendValidator struct {
	mock.Mock
}

// ValidateUserBackend provides a mock function with given fields: backend
func (_m *UserBackendValidator) ValidateUserBackend(backend context.UserBackend) error {
	ret := _m.Called(backend)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.UserBackend) error); ok {
		r0 = rf(backend)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
