// Code generated by mockery v2.42.1. DO NOT EDIT.

package validation

import (
	context "context"

	appcontext "github.com/cloudogu/k8s-ces-setup/app/context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoguValidator is an autogenerated mock type for the DoguValidator type
type MockDoguValidator struct {
	mock.Mock
}

type MockDoguValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguValidator) EXPECT() *MockDoguValidator_Expecter {
	return &MockDoguValidator_Expecter{mock: &_m.Mock}
}

// ValidateDogus provides a mock function with given fields: ctx, dogus
func (_m *MockDoguValidator) ValidateDogus(ctx context.Context, dogus appcontext.Dogus) error {
	ret := _m.Called(ctx, dogus)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDogus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.Dogus) error); ok {
		r0 = rf(ctx, dogus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguValidator_ValidateDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDogus'
type MockDoguValidator_ValidateDogus_Call struct {
	*mock.Call
}

// ValidateDogus is a helper method to define mock.On call
//   - ctx context.Context
//   - dogus appcontext.Dogus
func (_e *MockDoguValidator_Expecter) ValidateDogus(ctx interface{}, dogus interface{}) *MockDoguValidator_ValidateDogus_Call {
	return &MockDoguValidator_ValidateDogus_Call{Call: _e.mock.On("ValidateDogus", ctx, dogus)}
}

func (_c *MockDoguValidator_ValidateDogus_Call) Run(run func(ctx context.Context, dogus appcontext.Dogus)) *MockDoguValidator_ValidateDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(appcontext.Dogus))
	})
	return _c
}

func (_c *MockDoguValidator_ValidateDogus_Call) Return(_a0 error) *MockDoguValidator_ValidateDogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguValidator_ValidateDogus_Call) RunAndReturn(run func(context.Context, appcontext.Dogus) error) *MockDoguValidator_ValidateDogus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguValidator creates a new instance of MockDoguValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguValidator {
	mock := &MockDoguValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
