// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"

	mock "github.com/stretchr/testify/mock"
)

// RegistryWriter is an autogenerated mock type for the RegistryWriter type
type RegistryWriter struct {
	mock.Mock
}

// WriteConfigToRegistry provides a mock function with given fields: registryConfig
func (_m *RegistryWriter) WriteConfigToRegistry(registryConfig context.CustomKeyValue) error {
	ret := _m.Called(registryConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.CustomKeyValue) error); ok {
		r0 = rf(registryConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
