// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SSLGenerator is an autogenerated mock type for the SSLGenerator type
type SSLGenerator struct {
	mock.Mock
}

// GenerateSelfSignedCert provides a mock function with given fields: fqdn, domain, certExpireDays
func (_m *SSLGenerator) GenerateSelfSignedCert(fqdn string, domain string, certExpireDays int) (string, string, error) {
	ret := _m.Called(fqdn, domain, certExpireDays)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, int) string); ok {
		r0 = rf(fqdn, domain, certExpireDays)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string, int) string); ok {
		r1 = rf(fqdn, domain, certExpireDays)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, int) error); ok {
		r2 = rf(fqdn, domain, certExpireDays)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
