// Code generated by mockery v2.20.0. DO NOT EDIT.

package component

import mock "github.com/stretchr/testify/mock"

// mockResourceRegistryClient is an autogenerated mock type for the resourceRegistryClient type
type mockResourceRegistryClient struct {
	mock.Mock
}

type mockResourceRegistryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockResourceRegistryClient) EXPECT() *mockResourceRegistryClient_Expecter {
	return &mockResourceRegistryClient_Expecter{mock: &_m.Mock}
}

// GetResourceFileContent provides a mock function with given fields: resourceURL
func (_m *mockResourceRegistryClient) GetResourceFileContent(resourceURL string) ([]byte, error) {
	ret := _m.Called(resourceURL)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(resourceURL)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(resourceURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(resourceURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockResourceRegistryClient_GetResourceFileContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceFileContent'
type mockResourceRegistryClient_GetResourceFileContent_Call struct {
	*mock.Call
}

// GetResourceFileContent is a helper method to define mock.On call
//   - resourceURL string
func (_e *mockResourceRegistryClient_Expecter) GetResourceFileContent(resourceURL interface{}) *mockResourceRegistryClient_GetResourceFileContent_Call {
	return &mockResourceRegistryClient_GetResourceFileContent_Call{Call: _e.mock.On("GetResourceFileContent", resourceURL)}
}

func (_c *mockResourceRegistryClient_GetResourceFileContent_Call) Run(run func(resourceURL string)) *mockResourceRegistryClient_GetResourceFileContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockResourceRegistryClient_GetResourceFileContent_Call) Return(_a0 []byte, _a1 error) *mockResourceRegistryClient_GetResourceFileContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockResourceRegistryClient_GetResourceFileContent_Call) RunAndReturn(run func(string) ([]byte, error)) *mockResourceRegistryClient_GetResourceFileContent_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockResourceRegistryClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockResourceRegistryClient creates a new instance of mockResourceRegistryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockResourceRegistryClient(t mockConstructorTestingTnewMockResourceRegistryClient) *mockResourceRegistryClient {
	mock := &mockResourceRegistryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
