// Code generated by mockery v2.53.3. DO NOT EDIT.

package component

import (
	context "context"

	client "github.com/cloudogu/k8s-component-operator/pkg/helm/client"

	mock "github.com/stretchr/testify/mock"
)

// mockHelmClient is an autogenerated mock type for the helmClient type
type mockHelmClient struct {
	mock.Mock
}

type mockHelmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHelmClient) EXPECT() *mockHelmClient_Expecter {
	return &mockHelmClient_Expecter{mock: &_m.Mock}
}

// GetLatestVersion provides a mock function with given fields: chartName
func (_m *mockHelmClient) GetLatestVersion(chartName string) (string, error) {
	ret := _m.Called(chartName)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(chartName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(chartName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chartName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockHelmClient_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type mockHelmClient_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
//   - chartName string
func (_e *mockHelmClient_Expecter) GetLatestVersion(chartName interface{}) *mockHelmClient_GetLatestVersion_Call {
	return &mockHelmClient_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion", chartName)}
}

func (_c *mockHelmClient_GetLatestVersion_Call) Run(run func(chartName string)) *mockHelmClient_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockHelmClient_GetLatestVersion_Call) Return(_a0 string, _a1 error) *mockHelmClient_GetLatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockHelmClient_GetLatestVersion_Call) RunAndReturn(run func(string) (string, error)) *mockHelmClient_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// InstallOrUpgrade provides a mock function with given fields: ctx, chart
func (_m *mockHelmClient) InstallOrUpgrade(ctx context.Context, chart *client.ChartSpec) error {
	ret := _m.Called(ctx, chart)

	if len(ret) == 0 {
		panic("no return value specified for InstallOrUpgrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.ChartSpec) error); ok {
		r0 = rf(ctx, chart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockHelmClient_InstallOrUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallOrUpgrade'
type mockHelmClient_InstallOrUpgrade_Call struct {
	*mock.Call
}

// InstallOrUpgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - chart *client.ChartSpec
func (_e *mockHelmClient_Expecter) InstallOrUpgrade(ctx interface{}, chart interface{}) *mockHelmClient_InstallOrUpgrade_Call {
	return &mockHelmClient_InstallOrUpgrade_Call{Call: _e.mock.On("InstallOrUpgrade", ctx, chart)}
}

func (_c *mockHelmClient_InstallOrUpgrade_Call) Run(run func(ctx context.Context, chart *client.ChartSpec)) *mockHelmClient_InstallOrUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.ChartSpec))
	})
	return _c
}

func (_c *mockHelmClient_InstallOrUpgrade_Call) Return(_a0 error) *mockHelmClient_InstallOrUpgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockHelmClient_InstallOrUpgrade_Call) RunAndReturn(run func(context.Context, *client.ChartSpec) error) *mockHelmClient_InstallOrUpgrade_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHelmClient creates a new instance of mockHelmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHelmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHelmClient {
	mock := &mockHelmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
