// Code generated by mockery v2.20.0. DO NOT EDIT.

package setup

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigurationValidator is an autogenerated mock type for the setupJsonConfigurationValidator type
type MockConfigurationValidator struct {
	mock.Mock
}

type MockConfigurationValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurationValidator) EXPECT() *MockConfigurationValidator_Expecter {
	return &MockConfigurationValidator_Expecter{mock: &_m.Mock}
}

// ValidateConfiguration provides a mock function with given fields: configuration
func (_m *MockConfigurationValidator) Validate(configuration *context.SetupJsonConfiguration) error {
	ret := _m.Called(configuration)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.SetupJsonConfiguration) error); ok {
		r0 = rf(configuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigurationValidator_ValidateConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockConfigurationValidator_ValidateConfiguration_Call struct {
	*mock.Call
}

// ValidateConfiguration is a helper method to define mock.On call
//   - configuration *context.SetupJsonConfiguration
func (_e *MockConfigurationValidator_Expecter) ValidateConfiguration(configuration interface{}) *MockConfigurationValidator_ValidateConfiguration_Call {
	return &MockConfigurationValidator_ValidateConfiguration_Call{Call: _e.mock.On("Validate", configuration)}
}

func (_c *MockConfigurationValidator_ValidateConfiguration_Call) Run(run func(configuration *context.SetupJsonConfiguration)) *MockConfigurationValidator_ValidateConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*context.SetupJsonConfiguration))
	})
	return _c
}

func (_c *MockConfigurationValidator_ValidateConfiguration_Call) Return(_a0 error) *MockConfigurationValidator_ValidateConfiguration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigurationValidator_ValidateConfiguration_Call) RunAndReturn(run func(*context.SetupJsonConfiguration) error) *MockConfigurationValidator_ValidateConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockConfigurationValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConfigurationValidator creates a new instance of MockConfigurationValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConfigurationValidator(t mockConstructorTestingTNewMockConfigurationValidator) *MockConfigurationValidator {
	mock := &MockConfigurationValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
