#
# The default configuration map for the ces-setup. Should always be deployed before the setup itself.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-setup-config
  labels:
    app: ces
    app.kubernetes.io/name: k8s-ces-setup
data:
  k8s-ces-setup.yaml: |
    log_level: "DEBUG"
    component_operator_crd_chart: "k8s/k8s-component-operator-crd:latest"
    component_operator_chart: "k8s/k8s-component-operator:latest"
    components:
      k8s-dogu-operator-crd:
        version: "latest"
        helmRepositoryNamespace: k8s
      k8s-etcd:
        version: "latest"
        helmRepositoryNamespace: k8s
      k8s-dogu-operator:
        version: "latest"
        helmRepositoryNamespace: k8s
      k8s-service-discovery:
        version: "latest"
        helmRepositoryNamespace: k8s
    etcd_client_image_repo: bitnami/etcd:3.5.2-debian-10-r0
    key_provider: pkcs1v15
    resource_patches:
      - phase: dogu
        resource:
          apiVersion: k8s.cloudogu.com/v1
          kind: Dogu
          name: nexus
        patches:
          - op: add
            path: /spec/additionalIngressAnnotations
            value:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
          - op: add
            path: /spec/resources
            value:
              dataVolumeSize: 5Gi
      - phase: loadbalancer
        resource:
          apiVersion: v1
          kind: Service
          name: ces-loadbalancer
        patches:
          - op: add
            path: /metadata/annotations
            value:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
