// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileClient is an autogenerated mock type for the FileClient type
type FileClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: url, username, password
func (_m *FileClient) Get(url string, username string, password string) ([]byte, error) {
	ret := _m.Called(url, username, password)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = rf(url, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(url, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
