apiVersion: v1
values:
  images:
    k8sCesSetup: cloudogu/k8s-ces-setup:4.1.0
    kubectl: bitnamilegacy/kubectl:1.33.4
patches:
  values.yaml:
    setup:
      image:
        registry: "{{ registryFrom .images.k8sCesSetup }}"
        repository: "{{ repositoryFrom .images.k8sCesSetup }}"
        tag: "{{ tagFrom .images.k8sCesSetup }}"
    kubectl_image: "{{ .images.kubectl }}"
