apiVersion: v1
values:
  images:
    k8sCesSetup: cloudogu/k8s-ces-setup:0.20.0
    kubectl: bitnami/kubectl:1.27.4
    etcdClient: bitnami/etcd:3.5.2-debian-10-r0
patches:
  values.yaml:
    k8s_ces_setup_image: "{{ .images.k8sCesSetup }}"
    kubectl_image: "{{ .images.kubectl }}"
    etcd_client_image_repo: "{{ .images.etcdClient }}"
