apiVersion: v1
values:
  images:
    k8sCesSetup: cloudogu/k8s-ces-setup:2.0.0
    kubectl: bitnami/kubectl:1.27.4
patches:
  values.yaml:
    setup:
      image:
        repository: "{{ registryFrom .images.k8sCesSetup }}/{{ repositoryFrom .images.k8sCesSetup }}"
        tag: "{{ tagFrom .images.k8sCesSetup }}"
    kubectl_image: "{{ .images.kubectl }}"
