log_level: "DEBUG"
dogu_operator_url: https://dogu.cloudogu.com/api/v1/k8s/k8s/k8s-dogu-operator
service_discovery_url: https://dogu.cloudogu.com/api/v1/k8s/k8s/k8s-service-discovery
etcd_server_url: https://raw.githubusercontent.com/cloudogu/k8s-etcd/develop/manifests/etcd.yaml
etcd_client_image_repo: bitnami/etcd:3.5.2-debian-10-r0
key_provider: pkcs1v15
resource_patches:
  - phase: dogu
    resource:
      apiVersion: k8s.cloudogu.com/v1
      kind: Dogu
      name: nexus
    patches:
      - op: add
        path: /spec/additionalIngressAnnotations
        value:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
  - phase: loadbalancer
    resource:
      apiVersion: v1
      kind: Service
      name: ces-loadbalancer
    patches:
      - op: add
        path: /metadata/annotations/service.beta.kubernetes.io~1azure-load-balancer-internal
        value: "true"