apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
data:
  # TODO: we need to change this too, if we change names of resources or labels
  entrypoint.sh: |
    #!/bin/bash
    STATE=$(kubectl get configmap k8s-setup-config -o jsonpath='{.data.state}');
    if [[ ${STATE} == "installed" ]]; then
      kubectl delete configmap k8s-ces-setup-json || true
      kubectl delete configmap k8s-setup-config || true
      kubectl delete deployments,services,configmaps,secrets,roles,rolebindings,clusterroles,clusterrolebindings,serviceaccounts -l app.kubernetes.io/name={{ include "k8s-ces-setup.name" . }} || true
      kubectl patch cronjob cleanup -p '{"spec" : {"suspend" : true }}'
      kubectl delete configmap {{ include "k8s-ces-setup.name" . }}-cleanup-script
      kubectl delete cronjob {{ include "k8s-ces-setup-finisher.name" . }}
      kubectl delete serviceaccount {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
      kubectl delete rolebinding {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
    else
      echo "setup seems not to be installed or successfully executed";
    fi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
  labels:
    {{- include "k8s-ces-setup-finisher.labels" .| nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - delete
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
  labels:
    {{- include "k8s-ces-setup-finisher.labels" .| nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
  labels:
    {{- include "k8s-ces-setup-finisher.labels" .| nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - configmaps
      - services
      - secrets
      - deployments
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
      - serviceaccounts
      - cronjobs
    verbs:
      - delete
      - get
      - list
  - apiGroups:
      - "*"
    resources:
      - cronjobs
    verbs:
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
  labels:
    {{- include "k8s-ces-setup-finisher.labels" .| nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
  labels:
    {{- include "k8s-ces-setup-finisher.labels" .| nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "k8s-ces-setup-finisher.name" . }}
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubectl-container
              image: {{ or .Values.kubectl_image "bitnami/kubectl:1.27.4"}}
              command:
                - /bin/entrypoint.sh
              volumeMounts:
                - name: cleanup-script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
          restartPolicy: Never
          serviceAccountName: {{ include "k8s-ces-setup.name" . }}-cleanup-script-finisher
          volumes:
            - name: cleanup-script
              configMap:
                defaultMode: 0550
                name: {{ include "k8s-ces-setup.name" . }}-cleanup-script