{{- if and .Values.helm_registry_secret.username .Values.helm_registry_secret.password }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: component-operator-helm-repository
  labels:
    app: ces
data:
  endpoint: "{{ .Values.helm_registry_secret.host }}"
  schema: "{{ .Values.helm_registry_secret.schema }}"
  plainHttp: "{{ .Values.helm_registry_secret.plainHttp }}"
  insecureTls: "{{ .Values.helm_registry_secret.insecureTls }}"
  {{- end }}