{{- if .Values.container_registry_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: ces-container-registries
  labels:
    app: ces
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{ include "docker_config_json" .Values.container_registry_secrets | b64enc }}
{{- end }}