{{- if and .Values.docker_registry_secret.username .Values.docker_registry_secret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-dogu-operator-docker-registry
type: kubernetes.io/dockerconfig.json
data:
  .dockerconfigjson: {{ include "docker_config_json" (list .Values.docker_registry_secret.url .Values.docker_registry_secret.username .Values.docker_registry_secret.password) | b64enc }}
{{- end }}