{{- if and .Values.dogu_registry_secret.username .Values.dogu_registry_secret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-dogu-operator-dogu-registry-test
type: Opaque
data:
  endpoint: {{ .Values.dogu_registry_secret.url | b64enc }}
  password: {{ .Values.dogu_registry_secret.password | b64enc }}
  username: {{ .Values.dogu_registry_secret.username | b64enc  }}
{{- end }}