{{- if and .Values.dogu_registry_secret.username .Values.dogu_registry_secret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-dogu-operator-dogu-registry
  labels:
    app: ces
type: Opaque
data:
  endpoint: {{ .Values.dogu_registry_secret.url | b64enc }}
  password: {{ .Values.dogu_registry_secret.password }}
  username: {{ .Values.dogu_registry_secret.username | b64enc  }}
  urlschema: {{ .Values.dogu_registry_secret.urlschema | default "default" | b64enc  }}
{{- end }}