{{- if and .Values.helm_registry_secret.username .Values.helm_registry_secret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: component-operator-helm-registry
  labels:
    app: ces
type: Opaque
data:
  config.json: |
    {{ include "helm_config_json" (list .Values.helm_registry_secret.url .Values.helm_registry_secret.username .Values.helm_registry_secret.password) | b64enc }}
{{- end }}