{{- if .Values.setup_json }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-setup-json
  labels:
    app: ces
    app.kubernetes.io/name: k8s-ces-setup
data:
  setup.json: |
    {{ .Values.setup_json | nindent 4 }}
{{- end }}