apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-setup-config
  labels:
    {{- include "labels" }}
data:
  k8s-ces-setup.yaml: |
    dogu_operator_url: https://dogu.cloudogu.com/api/v1/k8s/k8s/k8s-dogu-operator
    service_discovery_url: https://dogu.cloudogu.com/api/v1/k8s/k8s/k8s-service-discovery
    etcd_server_url: https://dogu.cloudogu.com/api/v1/k8s/k8s/k8s-etcd
{{/*    {{- if .Values.components }}*/}}
{{/*    components:*/}}
{{/*      {{- range $component, $tag := .Values.components}}*/}}
{{/*      {{ printf "%s%s%s" $component ":" $tag | nindent 6 }}*/}}
{{/*      {{- end }}*/}}
{{/*    {{- end }}*/}}
    log_level: {{ or .Values.log_level "ERROR"}}
    etcd_client_image_repo: {{ or .Values.etcd_client_image_repo "bitnami/etcd:3.5.2-debian-10-r0"}}
    key_provider: {{ or .Values.key_provider "pkcs1v15"}}
    resource_patches: {{ or .Values.resource_patches ""}}
