#
# The deployment for the setup
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ces-setup
  labels:
    app: ces
    app.kubernetes.io/name: k8s-ces-setup
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-ces-setup
  template:
    metadata:
      labels:
        app: ces
        app.kubernetes.io/name: k8s-ces-setup
    spec:
      containers:
        - name: k8s-ces-setup
          image: {{ or .Values.k8s_ces_setup_image "cloudogu/k8s-ces-setup:0.19.1"}}
          imagePullPolicy: IfNotPresent
          env:
            - name: GIN_MODE
              value: release
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: setup-webui
            failureThreshold: 60
            periodSeconds: 10
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/v1/health
              port: setup-webui
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health
              port: setup-webui
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: setup-webui
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /k8s-ces-setup.yaml
              name: k8s-ces-setup-config
              subPath: k8s-ces-setup.yaml
            - mountPath: /setup.json
              name: k8s-ces-setup-json
              subPath: setup.json
            - name: dogu-registry-cert
              mountPath: /etc/ssl/certs/dogu-registry-cert.pem
              subPath: dogu-registry-cert.pem
            - mountPath: "/tmp/.helmregistry"
              name: component-operator-helm-registry
              readOnly: true
      volumes:
        - configMap:
            name: k8s-ces-setup-config
          name: k8s-ces-setup-config
        - configMap:
            name: k8s-ces-setup-json
            optional: true
          name: k8s-ces-setup-json
        - name: dogu-registry-cert
          secret:
            secretName: dogu-registry-cert
            optional: true
        - name: component-operator-helm-registry
          secret:
            secretName: component-operator-helm-registry
      serviceAccountName: k8s-ces-setup
      nodeSelector:
        kubernetes.io/os: linux