apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: setup
      port: 8080
      targetPort: setup-webui
      nodePort: 30080
  selector:
    app.kubernetes.io/name: {{ include "k8s-ces-setup.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  namespace: kube-system
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - delete
---
#
# The cluster role helps the setup to provide the dogu operator with the dogu CRD
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cluster-resources
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
    # Specify these labels to grant permissions to the admin default role
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  # allow to install the dogu CRD from the dogu operator
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - create
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
  - apiGroups:
      - "*"
    resources:
      - ingressclasses
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - cert-manager.io
    resources:
      - clusterissuers
    verbs:
      - get
      - create
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cluster-non-resources
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
    # Specify these labels to grant permissions to the admin default role
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  # allow to install a metrics cluster role of the dogu operator
  # it would be more secure if this rule would be delegated from setup/dogu operator to the initial setup process
  - nonResourceURLs:
      - /metrics
    verbs:
      - create
      - patch
      - update
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-ces-setup.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  namespace: kube-system
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-ces-setup.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cluster-resources
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-ces-setup.name" . }}-cluster-resources
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-cluster-non-resources
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-ces-setup.name" . }}-cluster-non-resources
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}
    namespace: {{ .Release.Namespace }}