apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  namespace: kube-system
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-ces-setup.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-setup.name" . }}
    namespace: '{{ .Release.Namespace }}'