apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ces-setup.name" . }}
  labels:
    {{- include "k8s-ces-setup.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: setup
      port: 8080
      targetPort: setup-webui
      nodePort: 30080
  selector:
    app.kubernetes.io/name: {{ include "k8s-ces-setup.name" . }}