apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-setup-config
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
data:
  k8s-ces-setup.yaml: |
    component_operator_chart: "{{ .Values.component_operator_chart }}"
    component_operator_crd_chart: "{{ .Values.component_operator_crd_chart }}"
    loadbalancer_name: "{{ include "k8s-ces-loadbalancer.name" . }}"
    {{- if .Values.components }}
    components:
    {{- toYaml .Values.components | nindent 6}}
    {{- end }}
    log_level: {{ or .Values.log_level "INFO"}}
    etcd_client_image_repo: {{ or .Values.etcd_client_image_repo "bitnami/etcd:3.5.2-debian-10-r0"}}
    key_provider: {{ or .Values.key_provider "pkcs1v15"}}
    {{- if .Values.resource_patches }}
    resource_patches:
    {{- toYaml .Values.resource_patches | nindent 6}}
    {{- end }}