apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-ces-setup.name" . }}-config
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
data:
  k8s-ces-setup.yaml: |
    component_operator_chart: "{{ .Values.component_operator_chart }}"
    component_operator_crd_chart: "{{ .Values.component_operator_crd_chart }}"
    {{- if .Values.components }}
    components:
    {{- toYaml .Values.components | nindent 6}}
    {{- end }}
    log_level: {{ or .Values.log_level "INFO"}}
    {{- if .Values.resource_patches }}
    resource_patches:
    {{- toYaml .Values.resource_patches | nindent 6}}
    {{- end }}