{{- if .Values.setup_json }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-setup-json
  labels:
    {{- include "k8s-ces-setup.labels" .| nindent 4 }}
data:
  setup.json: |
  {{- .Values.setup_json | nindent 4 }}
{{- end }}