// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "github.com/cloudogu/k8s-ces-setup/app/context"
	mock "github.com/stretchr/testify/mock"
)

// ConfigurationValidator is an autogenerated mock type for the ConfigurationValidator type
type ConfigurationValidator struct {
	mock.Mock
}

// ValidateConfiguration provides a mock function with given fields: configuration
func (_m *ConfigurationValidator) ValidateConfiguration(configuration *context.SetupConfiguration) error {
	ret := _m.Called(configuration)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.SetupConfiguration) error); ok {
		r0 = rf(configuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
